from api.tests.test_cases import CASES
from api.services.intent_classifier import classify_intent, INTENT_CONFIG
from api.services.prompt_builder import prompt_building
from api.services.rag_service import generate_answer
from api.services.vector_store import retrieve_relevant_documents


def evaluate_intent(actual_intent: str, expected_intent: str) -> bool: # compare actual intent with expected intent
    return actual_intent == expected_intent


def evaluate_answer_keywords(actual_answer: str, expected_keywords: list[str]):
    missing = []

    for keyword in expected_keywords: # loop through all keywords from the list of expected keywords and compare it to the actual answer
        if keyword.lower() not in actual_answer.lower():
            missing.append(keyword)

    if (len(expected_keywords) - len(missing))/len(expected_keywords) >= 0.80: # 80% accuracy was the determined threshold with Cleint for accuracy in terms of keywords
        return True, missing 

    return False, missing # return False if accuracy is below 0.8 and return a list of all missing keywords
 

def build_context_from_docs(question: str, intent: str) -> str:
    docs = retrieve_relevant_documents(question, INTENT_CONFIG[intent]["retrieval_k"]) # acquire the retrieved context for the prompt builder
    return "\n\n".join([doc.page_content for doc in docs]) # acquire the context in text form for use in the prompt/response


def run_tests():
    results = [] # acquire a list of all the results

    for case in CASES: # loop through all test cases
        # acquire the needed details 
        question = case["question"]
        expected_intent = case["expected_intent"]
        expected_keywords = case["expected_keywords"]
        test_intent = classify_intent(question).intent # find the intent for the question to use in prompt building

        context_text = build_context_from_docs(question, test_intent) # create the text version of the retrieved context for use in prompt building
        built_prompt = prompt_building( # dynamic prompt building, User Story 8 working(Woohoo!)
            question=question,
            context=context_text,
            intent=test_intent
        )
        response = generate_answer(question) # generate response and run full pipeline. Returns intent, response, prompt, and sources
        actual_answer = response["answer"] # answer received

        # test for intent, prompt accuracy, and matching keywords to test response accuracy based on test_file information
        intent_check = evaluate_intent(response["intent"], expected_intent) # Returns True if intent is matching, false if not
        answer_check, missing_keywords = evaluate_answer_keywords( # Returns True and an empty list if there are no missing keywords. For False, returns the missing keywords
            actual_answer,
            expected_keywords
        )

        prompt_check = response["prompt"] == built_prompt

        results.append({ # list of information for the result of each test
            "id": case["id"], 
            "question": question,
            "actual_intent": response["intent"], # intent from testing intent_classification
            "intent_correct": intent_check,
            "answer_correct": answer_check, # based on missing keywords
            "missing_keywords": missing_keywords, # list of all missing keywords
            "built_prompt": built_prompt, # the actual prompt
            "prompt_check": prompt_check, # the prompt generated by prompt_builder and the generated should be the same
            "answer": actual_answer, # generated response
        })

    return results # return all the results to be displayed


if __name__ == "__main__": # Test Results should be displayed, hence main method should be used
    results = run_tests() # run all tests and receive a dict of information

    passed = 0 # Counter for all passed tests
    total = len(results) # total amount of results/test cases

    for result in results:
        print("-" * 80) # a line of --------...
        print("-" * 80) # a line of --------...
        print(f"TEST #{result['id']}") # Test Number
        print(f"Question: {result['question']}") # Question tested
        print(f"Actual Intent: {result['actual_intent']}") # Intent Found 
        print(f"Correct Intent Found: {result['intent_correct']}") # Intent Check
        print(f">= 80% Accurate Answer Check: {result['answer_correct']}") # 80% Accuracy Response Check
        print(f"Missing Keywords: {result['missing_keywords']}")
        print(f"Prompt Match: {result['prompt_check']}") # Check that the prompt was matching
        print("\nBUILT PROMPT:\n")
        print(result["built_prompt"]) # Display the prompt used
        print("\nMODEL ANSWER:\n")
        print(result["answer"]) # display the received response
        print("-" * 80) # a line of --------...
        print("-" * 80) # a line of --------...

        if result["intent_correct"] and result["answer_correct"] and result["prompt_check"]: # For all checks passed
            passed += 1 # add 1 passed test to the tally


    print(f"\nPassed {passed}/{total} tests.") # Give the total number of passed tests out of the total